---
title: "Mi primer tutorial"
subtitle: "Facultad de Economía, UNAM\n"
author: "Cesar Hernández\n"
date: "3/03/2021\n"
output: learnr::tutorial
runtime: shiny_prerendered
description: >
  Aprende .......
---

```{r setup, include=FALSE}
library(learnr)
```

## Parte 1

*Código*

Modelo lineal simple

```{r modelo, exercise=TRUE}
modelo <- stats::lm(mpg ~ qsec, mtcars)
graphics::plot(modelo)
```

## Parte 2

*Pregunta*

Responde la pregunta

```{r pregunta, echo=FALSE}
learnr::question("¿Para qué sirve el software de R?",
  answer("Para hacer pasteles"),
  answer("Para nada"),
  answer("Para el análisis estadístico", correct = TRUE),
  answer("Para reproducir música")
)
```

## Parte 3

*Cuestionario*

Responde el cuestionario

```{r cuestionario, echo=FALSE}
learnr::quiz(
  question("¿Con qué función puedes graficar?", answer("var"), answer("median"), answer("plot", correct = TRUE), answer("summary")), 
  question("¿Con qué función puedes obtener el resumen estadístico de una serie de variables?", answer("summary", correct = TRUE), answer("cor"), answer("anova"), answer("head")),
  question("¿Con qué función puedes hacer una gráfica de barras?", answer("plot"), answer("pie"), answer("mean"), answer("barplot", correct = TRUE))
)
```
